<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Anexo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get anexo by id_anexos
     */
    function get_anexo($id_anexos)
    {
        return $this->db->get_where('anexos',array('id_anexos'=>$id_anexos))->row_array();
    }
        
    /*
     * Get all anexos
     */
    function get_all_anexos()
    {
        $this->db->order_by('id_anexos', 'desc');
        return $this->db->get('anexos')->result_array();
    }
        
    /*
     * function to add new anexo
     */
    function add_anexo($params)
    {
        $this->db->insert('anexos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update anexo
     */
    function update_anexo($id_anexos,$params)
    {
        $this->db->where('id_anexos',$id_anexos);
        return $this->db->update('anexos',$params);
    }
    
    /*
     * function to delete anexo
     */
    function delete_anexo($id_anexos)
    {
        return $this->db->delete('anexos',array('id_anexos'=>$id_anexos));
    }
}
