<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Endereco_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get endereco by id_endereco
     */
    function get_endereco($id_endereco)
    {
        return $this->db->get_where('enderecos',array('id_endereco'=>$id_endereco))->row_array();
    }

    /*
    * Get all enderecos
    */
   function get_all_enderecos($params = array())
   {
       $this->db->order_by('id_endereco', 'desc');
       if(isset($params) && !empty($params))
       {
           $this->db->limit($params['limit'], $params['offset']);
       }
       return $this->db->get('enderecos')->result_array();
   }

    /*
     * Get all enderecos count
     */
    function get_all_enderecos_count()
    {
        $this->db->from('enderecos');
        return $this->db->count_all_results();
    }

    /*
     * function to add new endereco
     */
    function add_endereco($params)
    {
        $this->db->insert('enderecos',$params);
        $id_retornado = $this->db->insert_id();
        return $id_retornado;
        // return $this->db->insert_id();
    }

    // get data by id
    function buscaPeloID($id_endereco)
    {
        $this->db->where($this->id_endereco, $id_endereco);
        return $this->db->get($this->table)->row();
    }

    /*
     * function to update endereco
     */
    function update_endereco($id_endereco,$params)
    {
        $this->db->where('id_endereco',$id_endereco);
        return $this->db->update('enderecos',$params);
    }

    /*
     * function to delete endereco
     */
    function delete_endereco($id_endereco)
    {
        return $this->db->delete('enderecos',array('id_endereco'=>$id_endereco));
    }
}
