<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Funcionario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get funcionario by id_funcionario
     */
    function get_funcionario($id_funcionario)
    {
        return $this->db->get_where('funcionarios',array('id_funcionario'=>$id_funcionario))->row_array();
    }
    
    /*
     * Get all funcionarios count
     */
    function get_all_funcionarios_count()
    {
        $this->db->from('funcionarios');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all funcionarios
     */
    function get_all_funcionarios($params = array())
    {
        $this->db->order_by('id_funcionario', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('funcionarios')->result_array();
    }
        
    /*
     * function to add new funcionario
     */
    function add_funcionario($params)
    {
        $this->db->insert('funcionarios',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update funcionario
     */
    function update_funcionario($id_funcionario,$params)
    {
        $this->db->where('id_funcionario',$id_funcionario);
        return $this->db->update('funcionarios',$params);
    }
    
    /*
     * function to delete funcionario
     */
    function delete_funcionario($id_funcionario)
    {
        return $this->db->delete('funcionarios',array('id_funcionario'=>$id_funcionario));
    }
}
