<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Os_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get os by id_os
     */
    function get_os($id_os)
    {
        return $this->db->get_where('os',array('id_os'=>$id_os))->row_array();
    }
    
    /*
     * Get all os count
     */
    function get_all_os_count()
    {
        $this->db->from('os');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all os
     */
    function get_all_os($params = array())
    {
        $this->db->order_by('id_os', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('os')->result_array();
    }
        
    /*
     * function to add new os
     */
    function add_os($params)
    {
        $this->db->insert('os',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update os
     */
    function update_os($id_os,$params)
    {
        $this->db->where('id_os',$id_os);
        return $this->db->update('os',$params);
    }
    
    /*
     * function to delete os
     */
    function delete_os($id_os)
    {
        return $this->db->delete('os',array('id_os'=>$id_os));
    }
}
