<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pagamento by id_lancamento
     */
    function get_pagamento($id_lancamento)
    {
        return $this->db->get_where('pagamentos',array('id_lancamento'=>$id_lancamento))->row_array();
    }
    
    /*
     * Get all pagamentos count
     */
    function get_all_pagamentos_count()
    {
        $this->db->from('pagamentos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all pagamentos
     */
    function get_all_pagamentos($params = array())
    {
        $this->db->order_by('id_lancamento', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('pagamentos')->result_array();
    }
        
    /*
     * function to add new pagamento
     */
    function add_pagamento($params)
    {
        $this->db->insert('pagamentos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pagamento
     */
    function update_pagamento($id_lancamento,$params)
    {
        $this->db->where('id_lancamento',$id_lancamento);
        return $this->db->update('pagamentos',$params);
    }
    
    /*
     * function to delete pagamento
     */
    function delete_pagamento($id_lancamento)
    {
        return $this->db->delete('pagamentos',array('id_lancamento'=>$id_lancamento));
    }
}
