<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producao_os_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get producao_os by id_producao
     */
    function get_producao_os($id_producao)
    {
        return $this->db->get_where('producao_os',array('id_producao'=>$id_producao))->row_array();
    }
    
    /*
     * Get all producao_os count
     */
    function get_all_producao_os_count()
    {
        $this->db->from('producao_os');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all producao_os
     */
    function get_all_producao_os($params = array())
    {
        $this->db->order_by('id_producao', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('producao_os')->result_array();
    }
        
    /*
     * function to add new producao_os
     */
    function add_producao_os($params)
    {
        $this->db->insert('producao_os',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update producao_os
     */
    function update_producao_os($id_producao,$params)
    {
        $this->db->where('id_producao',$id_producao);
        return $this->db->update('producao_os',$params);
    }
    
    /*
     * function to delete producao_os
     */
    function delete_producao_os($id_producao)
    {
        return $this->db->delete('producao_os',array('id_producao'=>$id_producao));
    }
}
