<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servico_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get servico by id_servicos
     */
    function get_servico($id_servicos)
    {
        return $this->db->get_where('servicos',array('id_servicos'=>$id_servicos))->row_array();
    }
    
    /*
     * Get all servicos count
     */
    function get_all_servicos_count()
    {
        $this->db->from('servicos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all servicos
     */
    function get_all_servicos($params = array())
    {
        $this->db->order_by('id_servicos', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('servicos')->result_array();
    }
        
    /*
     * function to add new servico
     */
    function add_servico($params)
    {
        $this->db->insert('servicos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update servico
     */
    function update_servico($id_servicos,$params)
    {
        $this->db->where('id_servicos',$id_servicos);
        return $this->db->update('servicos',$params);
    }
    
    /*
     * function to delete servico
     */
    function delete_servico($id_servicos)
    {
        return $this->db->delete('servicos',array('id_servicos'=>$id_servicos));
    }
}
