<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servicos_os_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get servicos_os by id_servicos_os
     */
    function get_servicos_os($id_servicos_os)
    {
        return $this->db->get_where('servicos_os',array('id_servicos_os'=>$id_servicos_os))->row_array();
    }
    
    /*
     * Get all servicos_os count
     */
    function get_all_servicos_os_count()
    {
        $this->db->from('servicos_os');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all servicos_os
     */
    function get_all_servicos_os($params = array())
    {
        $this->db->order_by('id_servicos_os', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('servicos_os')->result_array();
    }
        
    /*
     * function to add new servicos_os
     */
    function add_servicos_os($params)
    {
        $this->db->insert('servicos_os',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update servicos_os
     */
    function update_servicos_os($id_servicos_os,$params)
    {
        $this->db->where('id_servicos_os',$id_servicos_os);
        return $this->db->update('servicos_os',$params);
    }
    
    /*
     * function to delete servicos_os
     */
    function delete_servicos_os($id_servicos_os)
    {
        return $this->db->delete('servicos_os',array('id_servicos_os'=>$id_servicos_os));
    }
}
