<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipos_pagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipos_pagamento by id_tipo_pagamento
     */
    function get_tipos_pagamento($id_tipo_pagamento)
    {
        return $this->db->get_where('tipos_pagamento',array('id_tipo_pagamento'=>$id_tipo_pagamento))->row_array();
    }
        
    /*
     * Get all tipos_pagamento
     */
    function get_all_tipos_pagamento()
    {
        $this->db->order_by('id_tipo_pagamento', 'desc');
        return $this->db->get('tipos_pagamento')->result_array();
    }
        
    /*
     * function to add new tipos_pagamento
     */
    function add_tipos_pagamento($params)
    {
        $this->db->insert('tipos_pagamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipos_pagamento
     */
    function update_tipos_pagamento($id_tipo_pagamento,$params)
    {
        $this->db->where('id_tipo_pagamento',$id_tipo_pagamento);
        return $this->db->update('tipos_pagamento',$params);
    }
    
    /*
     * function to delete tipos_pagamento
     */
    function delete_tipos_pagamento($id_tipo_pagamento)
    {
        return $this->db->delete('tipos_pagamento',array('id_tipo_pagamento'=>$id_tipo_pagamento));
    }
}
