<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidades_medida_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidades_medida by id_unidade_medida
     */
    function get_unidades_medida($id_unidade_medida)
    {
        return $this->db->get_where('unidades_medida',array('id_unidade_medida'=>$id_unidade_medida))->row_array();
    }
        
    /*
     * Get all unidades_medida
     */
    function get_all_unidades_medida()
    {
        $this->db->order_by('id_unidade_medida', 'desc');
        return $this->db->get('unidades_medida')->result_array();
    }
        
    /*
     * function to add new unidades_medida
     */
    function add_unidades_medida($params)
    {
        $this->db->insert('unidades_medida',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidades_medida
     */
    function update_unidades_medida($id_unidade_medida,$params)
    {
        $this->db->where('id_unidade_medida',$id_unidade_medida);
        return $this->db->update('unidades_medida',$params);
    }
    
    /*
     * function to delete unidades_medida
     */
    function delete_unidades_medida($id_unidade_medida)
    {
        return $this->db->delete('unidades_medida',array('id_unidade_medida'=>$id_unidade_medida));
    }
}
