<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Enderecos_cliente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Enderecos_cliente_model');
    } 

    /*
     * Listing of enderecos_cliente
     */
    function index()
    {
        $data['enderecos_cliente'] = $this->Enderecos_cliente_model->get_all_enderecos_cliente();
        
        $data['_view'] = 'enderecos_cliente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new enderecos_cliente
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'endereco_id_cliente' => $this->input->post('endereco_id_cliente'),
				'cliente_id_endereco' => $this->input->post('cliente_id_endereco'),
            );
            
            $enderecos_cliente_id = $this->Enderecos_cliente_model->add_enderecos_cliente($params);
            redirect('enderecos_cliente/index');
        }
        else
        {            
            $data['_view'] = 'enderecos_cliente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a enderecos_cliente
     */
    function edit($id_endereco_cliente)
    {   
        // check if the enderecos_cliente exists before trying to edit it
        $data['enderecos_cliente'] = $this->Enderecos_cliente_model->get_enderecos_cliente($id_endereco_cliente);
        
        if(isset($data['enderecos_cliente']['id_endereco_cliente']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'endereco_id_cliente' => $this->input->post('endereco_id_cliente'),
					'cliente_id_endereco' => $this->input->post('cliente_id_endereco'),
                );

                $this->Enderecos_cliente_model->update_enderecos_cliente($id_endereco_cliente,$params);            
                redirect('enderecos_cliente/index');
            }
            else
            {
                $data['_view'] = 'enderecos_cliente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The enderecos_cliente you are trying to edit does not exist.');
    } 

    /*
     * Deleting enderecos_cliente
     */
    function remove($id_endereco_cliente)
    {
        $enderecos_cliente = $this->Enderecos_cliente_model->get_enderecos_cliente($id_endereco_cliente);

        // check if the enderecos_cliente exists before trying to delete it
        if(isset($enderecos_cliente['id_endereco_cliente']))
        {
            $this->Enderecos_cliente_model->delete_enderecos_cliente($id_endereco_cliente);
            redirect('enderecos_cliente/index');
        }
        else
            show_error('The enderecos_cliente you are trying to delete does not exist.');
    }
    
}
