<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Endereco extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Endereco_model');
    }

    /*
     * Listing of enderecos
     */
    function index()
    {
        $params['limit'] = 30;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('endereco/index?');
        $config['total_rows'] = $this->Endereco_model->get_all_enderecos_count();
        $config['per_page'] = 30;

        $this->pagination->initialize($config);

        $data['enderecos'] = $this->Endereco_model->get_all_enderecos($params);

        $data['_view'] = 'endereco/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new endereco
     */
    // function add()
    // {
    // $this->load->library('form_validation');
    //
		// $this->form_validation->set_rules('numero','Numero','numeric');
		// $this->form_validation->set_rules('rua','Rua','required');
		// $this->form_validation->set_rules('cidade','Cidade','required');
		// $this->form_validation->set_rules('bairro','Bairro','required');
		// $this->form_validation->set_rules('uf','Uf','required');
    //
		// if($this->form_validation->run())
    //     {
    //         $params = array(
    //   				'rua' => $this->input->post('rua'),
    //   				'bairro' => $this->input->post('bairro'),
    //   				'cidade' => $this->input->post('cidade'),
    //   				'complemento' => $this->input->post('complemento'),
    //   				'numero' => $this->input->post('numero'),
    //   				'uf' => $this->input->post('uf'),
    //   				'cep' => $this->input->post('cep'),
    //         );
    //
    //
    //         $endereco_id = $this->Endereco_model->add_endereco($params);
    //
    //         // if ( is_numeric($cliente_id = $this->Cliente_model->add_cliente($params, true)) ) {
    //         //     redirect('cliente/edit/'.$cliente_id);
    //         //
    //         // } else {
    //         //
    //         //     $this->data['custom_error'] = '<div class="form_error"><p>An Error Occured.</p></div>';
    //         // }
    //         // redirect('endereco/index');
    //     }
    //     else
    //     {
    //         //$data['_view'] = 'endereco/add';
    //         $this->load->view('endereco/add');
    //     }
    // }

    /*
     * Adding a new enderecos_cliente
     */
    function addEnderecoCliente()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
        'endereco_id_cliente' => $this->input->post('endereco_id_cliente'),
        'cliente_id_endereco' => $this->input->post('cliente_id_endereco'),
            );

            $enderecos_cliente_id = $this->Enderecos_cliente_model->add_enderecos_cliente($params);
            redirect('enderecos_cliente/index');
        }
        else
        {
      $this->load->model('Endereco_model');
      $data['all_enderecos'] = $this->Endereco_model->get_all_enderecos();

      $this->load->model('Cliente_model');
      $data['all_clientes'] = $this->Cliente_model->get_all_clientes();

            $data['_view'] = 'enderecos_cliente/add';
            $this->load->view('layouts/main',$data);
        }
    }


    /*
     * Editing a endereco
     */
    function edit($id_endereco)
    {
        // check if the endereco exists before trying to edit it
        $data['endereco'] = $this->Endereco_model->get_endereco($id_endereco);

        if(isset($data['endereco']['id_endereco']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('numero','Numero','numeric');
			$this->form_validation->set_rules('rua','Rua','required');
			$this->form_validation->set_rules('cidade','Cidade','required');
			$this->form_validation->set_rules('bairro','Bairro','required');
			$this->form_validation->set_rules('uf','Uf','required');

			if($this->form_validation->run())
            {
                $params = array(
        					'rua' => $this->input->post('rua'),
        					'bairro' => $this->input->post('bairro'),
        					'cidade' => $this->input->post('cidade'),
        					'complemento' => $this->input->post('complemento'),
        					'numero' => $this->input->post('numero'),
        					'uf' => $this->input->post('uf'),
        					'cep' => $this->input->post('cep'),
                );

                // if ( is_numeric($id_endereco = $this->Endereco_model->add_endereco($params, true)) ) {
                //
                //
                // } else {
                //
                //     $this->data['custom_error'] = '<div class="form_error"><p>An Error Occured.</p></div>';
                // }

                $this->Endereco_model->update_endereco($id_endereco,$params);
                redirect('cliente/index');
            }
            else
            {
                $this->load->model('Endereco_model');
          			$data['all_enderecos'] = $this->Endereco_model->get_all_enderecos();

          			$this->load->model('Cliente_model');
          			$data['all_clientes'] = $this->Cliente_model->get_all_clientes();

                $data['_view'] = 'endereco/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The endereco you are trying to edit does not exist.');
    }



    /*
     * Ler produto
     */
    public function lerEndereco($id_endereco)
    {

        $row = $this->Endereco_model->buscaPeloID($id_endereco);
        if ($row) {
            $data = array(
                'id_endereco' => $row->id_endereco,
                'rua' => $row->rua,
                    );


        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('produtos'));
        }
    }



    /*
     * Deleting endereco
     */
    function remove($id_endereco)
    {
        $endereco = $this->Endereco_model->get_endereco($id_endereco);

        // check if the endereco exists before trying to delete it
        if(isset($endereco['id_endereco']))
        {
            $this->Endereco_model->delete_endereco($id_endereco);

            redirect('cliente/index');
        }
        else
            show_error('The endereco you are trying to delete does not exist.');
    }

}
